#!/bin/bash
# Generates two PDFs from a single investor-pack.html source:
#
#   figueretes-property.pdf         → Private buyers @ €479,000 / 7.3% gross / 5.8% net
#                                     (matches the live xuriare.com/figueretes page)
#
#   figueretes-property-agency.pdf  → Agencies / brokers  @ €499,000 / 7.0% gross / 5.6% net
#                                     (generated by sed-substitution from the source)
#
# Run from the repo root after editing investor-pack.html.

set -e
cd "$(dirname "$0")"

CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

echo "→ Generating private PDF (€479,000)…"
"$CHROME" \
  --headless=new --disable-gpu --no-pdf-header-footer --print-to-pdf-no-header \
  --print-to-pdf="figueretes-property.pdf" \
  --virtual-time-budget=15000 --hide-scrollbars \
  "file://$(pwd)/investor-pack.html" > /dev/null 2>&1

echo "→ Generating agency PDF (€499,000)…"
# Build the agency source by swapping price + yields.
AGENCY_SRC="investor-pack-agency.html"
sed -e 's/€479,000/€499,000/g' \
    -e 's|>7\.3%<|>7.0%<|g' \
    -e 's|>5\.8%<|>5.6%<|g' \
    investor-pack.html > "$AGENCY_SRC"

"$CHROME" \
  --headless=new --disable-gpu --no-pdf-header-footer --print-to-pdf-no-header \
  --print-to-pdf="figueretes-property-agency.pdf" \
  --virtual-time-budget=15000 --hide-scrollbars \
  "file://$(pwd)/$AGENCY_SRC" > /dev/null 2>&1

rm "$AGENCY_SRC"

echo
echo "✓ Done."
ls -lh figueretes-property.pdf figueretes-property-agency.pdf
